# Generated by Django 4.2.9 on 2026-04-01 13:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('job_alert', 'New Job Near You'), ('application_received', 'New Application'), ('application_accepted', 'Application Accepted'), ('job_started', 'Job Started'), ('job_completed', 'Job Completed'), ('payment_held', 'Payment Secured'), ('payment_released', 'Payment Released'), ('new_message', 'New Message'), ('review_received', 'New Review')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('data', models.JSONField(default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
